import pymupdf
import pytest
from PIL import Image, ImageDraw, ImageFont

import indexer_config as cfg
from extract import extract, ExtractError

PY_SRC = '''import os
import sys

MAX = 10


def add(a, b):
    """Add two numbers."""
    return a + b


class PaymentService:
    def charge(self, amount):
        return amount * 2

    def refund(self, amount):
        return -amount
'''


def _text_image(text: str, path) -> None:
    img = Image.new("RGB", (900, 260), "white")
    try:
        font = ImageFont.truetype("arial.ttf", 48)
    except Exception:
        font = None
    ImageDraw.Draw(img).text((30, 90), text, fill="black", font=font)
    img.save(path)


def test_python_symbols_and_outline(make):
    chunks = extract(make("a.py", PY_SRC))
    kinds = {c.kind for c in chunks}
    assert "outline" in kinds and "code" in kinds
    outline = next(c for c in chunks if c.kind == "outline")
    assert "PaymentService" in outline.text and "import os" in outline.text
    joined = "\n".join(c.text for c in chunks if c.kind == "code")
    assert "def charge" in joined and "def add" in joined


def test_large_class_split_into_methods(make):
    methods = "\n".join(f"    def m{i}(self):\n        return {i} * 'x' * 20\n" for i in range(400))
    chunks = extract(make("big.py", "class Big:\n    '''doc'''\n\n" + methods))
    symbols = {c.symbol for c in chunks}
    assert any(s.startswith("Big.m") for s in symbols)
    assert all(len(c.text) <= cfg.MAX_CHUNK_CHARS for c in chunks)
    assert len(chunks) <= cfg.MAX_CHUNKS_PER_FILE


def test_typescript_arrow_function(make):
    src = "export const greet = (n: string) => {\n  return `hi ${n}`;\n};\n\nexport class A { run() { return 1; } }\n"
    chunks = extract(make("a.ts", src))
    assert any("greet" in c.symbol for c in chunks if c.kind == "code")


def test_minified_rejected(make):
    with pytest.raises(ExtractError):
        extract(make("bundle.js", "var a=1;" * 5000))


def test_generated_header_rejected(make):
    with pytest.raises(ExtractError):
        extract(make("g.py", "# @generated by tool\nx = 1\n"))


def test_binary_rejected(tmp_path):
    p = tmp_path / "b.txt"
    p.write_bytes(b"abc\x00def")
    with pytest.raises(ExtractError):
        extract(str(p))


def test_markdown_heading_path(make):
    chunks = extract(make("n.md", "# Top\nintro text here\n\n## Sub\n" + "detail line\n" * 5 +
                          "\n```\n# not a heading\n```\n"))
    assert any("Top > Sub" in c.symbol for c in chunks)
    assert not any("not a heading" in c.symbol for c in chunks)


def test_notebook_skips_outputs(make):
    import json
    nb = {"cells": [{"cell_type": "code", "source": ["print('hi')"], "outputs": [{"data": {"image/png": "A" * 5000}}]},
                    {"cell_type": "markdown", "source": "# Title"}]}
    chunks = extract(make("n.ipynb", json.dumps(nb)))
    assert chunks and all("AAAA" not in c.text for c in chunks)


def test_dockerfile_and_json(make):
    assert extract(make("Dockerfile", "FROM python:3.12\nRUN pip install x\n"))
    assert extract(make("c.json", '{"a": 1}\n'))


def test_data_file_too_large(tmp_path):
    p = tmp_path / "d.json"
    p.write_text('{"a": "' + "x" * (cfg.MAX_DATA_FILE_KB * 1024) + '"}')
    with pytest.raises(ExtractError):
        extract(str(p))


def test_pdf_text_pages_and_image_ocr(tmp_path):
    img = tmp_path / "fig.png"
    _text_image("Quarterly revenue forecast", img)
    pdf = tmp_path / "doc.pdf"
    doc = pymupdf.open()
    p1 = doc.new_page()
    p1.insert_text((72, 72), "Introduction to the budget process")
    p2 = doc.new_page()
    p2.insert_text((72, 72), "Appendix with a diagram shown below in this document")
    p2.insert_image(pymupdf.Rect(72, 100, 472, 300), filename=str(img))
    doc.save(str(pdf))
    chunks = extract(str(pdf))
    assert any(c.page == 1 and "budget" in c.text for c in chunks)
    fig = [c for c in chunks if c.kind == "image"]
    assert fig and fig[0].page == 2 and "revenue" in fig[0].text.lower()


def test_scanned_pdf_page_is_ocrd(tmp_path):
    img = tmp_path / "scan.png"
    _text_image("Scanned contract clause seven", img)
    pdf = tmp_path / "scan.pdf"
    doc = pymupdf.open()
    page = doc.new_page()
    page.insert_image(page.rect, filename=str(img))
    doc.save(str(pdf))
    chunks = extract(str(pdf))
    assert any("contract" in c.text.lower() and c.page == 1 for c in chunks)


def test_docx_headings_and_image(tmp_path):
    import docx
    img = tmp_path / "pic.png"
    _text_image("Network topology diagram", img)
    d = docx.Document()
    d.add_heading("Design", level=1)
    d.add_paragraph("We use a hub and spoke layout.")
    d.add_heading("Details", level=2)
    d.add_paragraph("Latency matters most.")
    d.add_picture(str(img))
    out = tmp_path / "a.docx"
    d.save(str(out))
    chunks = extract(str(out))
    assert any(c.symbol == "Design > Details" for c in chunks)
    assert any(c.kind == "image" and "topology" in c.text.lower() for c in chunks)


def test_pptx_slides(tmp_path):
    from pptx import Presentation
    prs = Presentation()
    s = prs.slides.add_slide(prs.slide_layouts[1])
    s.shapes.title.text = "Roadmap"
    s.placeholders[1].text = "Ship the indexer"
    out = tmp_path / "a.pptx"
    prs.save(str(out))
    chunks = extract(str(out))
    assert chunks[0].page == 1 and "indexer" in chunks[0].text


def test_standalone_image(tmp_path):
    p = tmp_path / "shot.png"
    _text_image("Error: connection refused", p)
    chunks = extract(str(p))
    assert chunks[0].kind == "image" and "connection refused" in chunks[0].text.lower()
